apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:
  containers:
  - name: website
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: meupod-02
  labels:
    app: meusegundopod
spec:
  containers:
  - name: website
    image: nginx
    ports:
    - containerPort: 80